### ISSUE TITLE
Not an Issue __ just a Big thank you with

### ISSUE THREAD

**Issue by mkwsra** [Silentscripter/laravel-prestashop-webservice#1]
I just wanted to say Hi and big thanks to you for doing such kind of thing 👍

**Comment by mkwsra** [comment]
@Silentscripter Buddy, I'm trying to install this library but I'm getting an error!
Can you help me determine what is my problem?

I'm running:
Ubuntu 14.04.4 LTS
PHP 7.0.4
Laravel Framework version 5.2.32

<img width="1439" alt="screen shot 2016-05-20 at 01 11 49" src="https://cloud.githubusercontent.com/assets/1743919/15411370/2f4c7a36-1e28-11e6-99ad-8e934875a6c9.png">

**Comment by Silentscripter** [comment]
Hi mate, comments like yours are what make us developers love this job and be willing to help each other.
Please let me know if you have any request for this package, I'll be glad to help
