### ISSUE TITLE
JSON output format

### ISSUE THREAD

**Issue by SaeedDev94** [Silentscripter/laravel-prestashop-webservice#10]
How can i receive response as JSON format?
I tried this code but no luck, still receiving as XML
```php
$options = [
    	'resource' => 'products',
    	'output_format' => 'JSON'
];
$products = Prestashop::get($options);
return var_dump($products);
```

**Comment by Silentscripter** [comment]
Hi, unfortunately it's not possible due to limitations of the underlying official PrestashopWebServiceLibrary.php
