### ISSUE TITLE
Make date filtering available by adding 'date' 

### ISSUE THREAD

**Issue by rokdevil** [Silentscripter/laravel-prestashop-webservice#14]
You have this line:
$params = array('filter', 'display', 'sort', 'limit', 'id_shop', 'id_group_shop');

If you update it to:
$params = array('filter', 'display', 'sort', 'limit', 'id_shop', 'id_group_shop', 'date');

then the library can be used for date filtering.  The user just needs to add $opt['date'] = 1 to the query params.

**Comment by Silentscripter** [comment]
It's not possible to filter by date if you don't modify the webservice class on prestashop itself. Even if you modify the line above to let this library pass the date to the filters you'll receive an error from prestashop saying "This filter does not exists"

**Comment by rokdevil** [comment]
I'm running version 1.6 and having no problem filtering by date.  Specifically, if you look in WebserviceRequest.php (in classes/webservice ) you'll find a commented line: 

> // Date feature : date=1

Likewise you'll find the same bit of code in PS version 1.541.  I'm not sure when it was added.

**Comment by Silentscripter** [comment]
Could you provide please an example of query string ina webservice request with a date filter? thanks

**Comment by Silentscripter** [comment]
Functionality added #16
