### ISSUE TITLE
Filtri / Filter

### ISSUE THREAD

**Issue by cirolosapio** [Silentscripter/laravel-prestashop-webservice#15]
Ciao, come posso fare una richiesta a prestashop applicando dei filtri?

**Comment by Silentscripter** [comment]
Ciao, puoi seguire l'esempio nella documentazione

[http://doc.prestashop.com/display/PS16/Chapter+8+-+Advanced+use#Chapter8-Advanceduse-RenderingFilters]()

**Comment by cirolosapio** [comment]
Ciao, seguito l'esempio in questo modo:

$xmlSchema = Prestashop::getSchema('products/?display=[id,reference]&filter[reference]=['.$product_cod.']');

ma senza successo. Ho notato però che nella richiesta l'ulrl è:

HTTP REQUEST HEADER
GET /api/products/?display=[id,reference]&filter[reference]=[ONEFORALL]?schema=blank HTTP/1.1

Avendo due caratteri '?' la richiesta fallisce. Come posso risolvere?

Grazie

**Comment by laravel-jquery** [comment]
Ciao, seguito l'esempio in questo modo:

$xmlSchema = Prestashop::getSchema('products/?display=[id,reference]&filter[reference]=['.$product_cod.']');

ma senza successo. Ho notato però che nella richiesta l'ulrl è:

HTTP REQUEST HEADER
GET /api/products/?display=[id,reference]&filter[reference]=[ONEFORALL]?schema=blank HTTP/1.1

Avendo due caratteri '?' la richiesta fallisce. Come posso risolvere?

Grazie

**Comment by laravel-jquery** [comment]
Ho risolto cosi:
$xmlSchema = Prestashop::getSchema('products','synopsis&display=[id,reference]&filter[reference]=[ONEFORALL]');

**Comment by Silentscripter** [comment]
Per concatenare parametri in una query string devi usare il carattere '&'
Nell'esempio sopra dovresti sostituire il secondo ? con un &.
Tuttavia non ha molto senso logico quello che hai scritto in quanto se stai facendo una query con dei filtri è per filtrare dei risultati quindi non ha senso aggiungere 'schema=blank' in quanto quello serve per richiedere lo scheletro base del file XML sul quale preparare i dati da inviare al server.

**Comment by cirolosapio** [comment]
?schema=blank viene messo da solo dalla classe PrestashopWebService.

**Comment by Silentscripter** [comment]
Probabilmente hai usato il metodo errato. Devi usare il metodo `get` per reperire dati, mentre `getSchema` solo per richiedere lo schema della risorsa

**Comment by cirolosapio** [comment]
ah ok adesso è chiaro
grazie
