### ISSUE TITLE
400 Bad Request PrestaShop Web Services

### ISSUE THREAD

**Issue by flug** [Silentscripter/laravel-prestashop-webservice#17]
Hello, 
I'm trying to implement your library, but I don't understand presashop returns a 400. I am on version 1.7 is it still compatible with this version? 
thx

**Comment by Silentscripter** [comment]
Hello flug, the library is compatible with 1.7. You should log the error response in the xml received from the server to debug the possible cause. Anyway error 400 means you've made a mistake constructing request data, probably missing a required field or something similar.
