### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by Justproof** [Silentscripter/laravel-prestashop-webservice#21]
Hello, I followed along with the installation instructions but I'm not sure where to put the usage section. 
Also, do I need to copy the contents of the src file into a controllers folder?

**Comment by Silentscripter** [comment]
Hello @Justproof, you don't have to put src folder in controllers, the package is loaded via composer under the hood as for any other package. The usage part is an example of using this library in a demo controller, you may use it whenever you need via the Laravel dependency injection system. I would, anyway, kindly suggest you to read the laravel documentation as your question denotes you still need to grasp the basics of the framework itself.

**Comment by Silentscripter** [comment]
Closing the issue, if you need further help feel free to reopen
