### ISSUE TITLE
Error when use 

### ISSUE THREAD

**Issue by jjmontalban** [Silentscripter/laravel-prestashop-webservice#30]
Hi

I have follow all step but when I use your library I obtain this error message:

![image](https://user-images.githubusercontent.com/2886221/63955406-f10a7900-ca84-11e9-8608-977f953812d2.png)

Any idea?

Best regards in advance

**Comment by Silentscripter** [comment]
Hi,
error 401 is linked with authentication issues. Possible reason may be the error in setting the API token in the configuration file. Please verify that token you use is allowed in the prestashop web service panel.

**Comment by jjmontalban** [comment]
My configuration in Prestashop is:

![image](https://user-images.githubusercontent.com/2886221/64014005-5b70f700-cb21-11e9-8e2e-19ac4f5ad625.png)

And I followed steps in in Laravel project:

![image](https://user-images.githubusercontent.com/2886221/64013910-29f82b80-cb21-11e9-9857-36a2df24f30d.png)

Its neccessary any config in server o some site?

**Comment by jjmontalban** [comment]
Solved!

Mode CGI must be enable

Sorry and Best regards
