### ISSUE TITLE
but these conflict with your requirements or minimum-stability

### ISSUE THREAD

**Issue by jorgerrubio** [Silentscripter/laravel-prestashop-webservice#4]
composer require protechstudio/laravel-prestashop-webservice
Using version ^2.2 for protechstudio/laravel-prestashop-webservice
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for protechstudio/laravel-prestashop-webservice ^2.2 -> satisfiable by protechstudio/laravel-prestashop-webservice[2.2.0].
    - protechstudio/laravel-prestashop-webservice 2.2.0 requires prestashop/prestashop-webservice-lib dev-master -> satisfiable by prestashop/prestashop-webservice-lib[dev-master] but these conflict with your requirements or minimum-stability

Installation failed, reverting ./composer.json to its original content.

**Comment by jorgerrubio** [comment]
problem solved by adding composer.json (laravel)
"minimum-stability": "dev",

**Comment by Silentscripter** [comment]
Yes, it's not a bug, Unfortunately the underlying Prestashop Webservice package is not versioned so you need to enforce "minimum-stability":"dev".
I suggest also adding "prefer-stable": true as this way composer will prefer stable packages, if found, over dev ones.

**Comment by Silentscripter** [comment]
Updated documentation to avoid people losing time with this
