### ISSUE TITLE
How can I filter by date range?

### ISSUE THREAD

**Issue by juanmanavarro** [Silentscripter/laravel-prestashop-webservice#5]
Any idea?

**Comment by Silentscripter** [comment]
As far as I now it's not possible due to the API limitations. If you try to filter by a date field you get back an error saying the filed is not in the valid filter list.

**Comment by Silentscripter** [comment]
We have added this feature in version 3.2.0. (see #16) 
Just pass `date=1` as a query string parameter to enable date filtering. @juanmanavarro

**Comment by Turaylon** [comment]
Example of URI with filtering on date: `/api/orders?display=[id,date_add]&sort=[date_add_DESC]&date=1&filter[date_add]=[2017-01-1,2018-4-4]`

**Comment by ghost** [comment]
And filter from i date to .. ALL
FECHA > '2017-01-01'
OR FECHA < '31-12-2022'
(not between)
i try to put empty second value  (triying with numbers and other field)
filter[date_add]=[2017-01-1,]
