### ISSUE TITLE
get() function

### ISSUE THREAD

**Issue by 1110815AdamSilva** [Silentscripter/laravel-prestashop-webservice#6]
Hey, I'm trying to use the get function to simply retrieve the list of all the customers:  
        public function get()
        {
            $opt['resource'] = 'customers';
            $data=$this->prestashop->get($opt);
            return view('admin.user.info')->with('data', $data);

```
    }
```

But it's retrieving also the request header, the response header and the http body, instead of returning a simple XML to treat the data. Attached is an image showing what I get. Am I doing something wrong?
![photo](https://cloud.githubusercontent.com/assets/3687887/18562455/ab2d6fc4-7b7b-11e6-96b1-2548e5d7c1f8.png)

**Comment by Silentscripter** [comment]
Hi, this happens because the debug property in the prestashop-webservice.php config file is set to true. You must set it to false to hide these messages.

**Comment by 1110815AdamSilva** [comment]
That's not the problem. The debug is set to false in the prestashop-webservice.php
