### ISSUE TITLE
Post Schema Returns HTTP status of 500

### ISSUE THREAD

**Issue by 1110815AdamSilva** [Silentscripter/laravel-prestashop-webservice#8]
Hey, I'm retrieving the schema for Products, I'm filling it up just as shown in the documentation, and it's returning me an Internal Error 500. Any idea why?

Here is my code:
`$xmlSchema=$this->prestashop->getSchema('products'); 

	$data=[
		'upc'=> 123123123123 ,
		'reference'=> 023546,
		'meta_title' => [
			1 => "Test",
			2 => "Teste"
		],
		'price' => 2.3,
		'wholesale_price' => 1.4,
		'id_tax_rules_group' => 1
	];

	$postXml=$this->prestashop->fillSchema($xmlSchema,$data); 

	//The xml is now ready for being sent back to the web service to create a new category
	$response=$this->prestashop->add(['resource'=>'products','postXml'=>$postXml->asXml()]);`

**This is what appears if I turn on debug:**

`HTTP REQUEST HEADER
POST /prestashop/api/products HTTP/1.1
Host: localhost
Authorization: Basic V0s1VTFBRFVEUzdUMjFQSkY3NDRCVzdJS0ZLVlVETTg6
Accept: */*
Content-Length: 512
Content-Type: application/x-www-form-urlencoded

HTTP RESPONSE HEADER
HTTP/1.1 500 Internal Server Error
Date: Tue, 08 Nov 2016 16:24:23 GMT
Server: Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.24
X-Powered-By: PrestaShop Webservice
Access-Time: 1478622263
PSWS-Version: 1.6.1.7
Execution-Time: 0.023
Set-Cookie: PrestaShop-bfbe109d475f74a42c8014cc428afcb4=3YSqzEP8FNMMPPGPNImrw%2FAbx%2FRV6E5tI0mw1X6YiDM08MM%2Bh%2FfB5KadofzZpnGLGAX%2B7YDIdifN2cw61KjuNJDTGSMpaJ6klP3T7mLSTEA%3D000079; expires=Mon, 28-Nov-2016 16:24:23 GMT; Max-Age=1728000; path=/prestashop/; httponly
Content-Length: 241
Connection: close
Content-Type: text/xml;charset=utf-8
XML SENT
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product>
	
	
	
	
	
	
	
	
	<id_tax_rules_group>1</id_tax_rules_group>
	
	
	
	<reference>az123</reference>
	
	
	
	
	
	
	
	<ean13></ean13>
	<upc>123123123123</upc>
	
	
	
	
	
	
	
	<price>1.2</price>
	<wholesale_price>3.4</wholesale_price>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	<meta_title><language id="1">Azeitonas</language><language id="2">Azeitonas</language></meta_title>
	
	
	
	
	
	

	</product>
	</prestashop>
	RETURN HTTP BODY
	<?xml version="1.0" encoding="UTF-8"?>
	<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
	<errors>
	<error>
	<message><![CDATA[Internal error. To see this error please display the PHP errors.]]></message>
	</error>
	</errors>
	</prestashop>`

**Comment by Silentscripter** [comment]
Hi man, go to the prestashop website root folder, open the `config/defines.inc.php` file, you should find these lines at the beginning:

``` php
/* Debug only */
if (!defined('_PS_MODE_DEV_')) {
define('_PS_MODE_DEV_', false);
```

Change the `_PS_MODE_DEV_` constant to `true` and repeat the webservice call, you will receive a detailed error message this time to help with issue debugging.
